import React from "react";
import { Bar } from "react-chartjs-2";



class ShowChart extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }

  render() {
    let labels = ["FAILURE TO DISPLAY BUS PERMIT",
"NO OPERATOR NAM/ADD/PH DISPLAY",
"UNAUTHORIZED PASSENGER PICK-UP",
"BUS PARKING IN LOWER MANHATTAN",
"BUS LANE VIOLATION",
"OVERNIGHT TRACTOR TRAILER PKG",
"FAILURE TO STOP AT RED LIGHT",
"IDLING",
"OBSTRUCTING TRAFFIC/INTERSECT",
"NO STOPPING-DAY/TIME LIMITS",
"NO STANDING-HOTEL LOADING",
"NO STANDING-SNOW EMERGENCY",
"NO STANDING-TAXI STAND",
"NO STANDING-DAY/TIME LIMITS",
"NO STANDING-OFF-STREET LOT",
"NO STANDING-EXC. TRUCK LOADING",
"NO STANDING-EXC. AUTH. VEHICLE",
"NO STANDING-BUS LANE",
"NO STANDING-BUS STOP",
"NO PARKING-DAY/TIME LIMITS",
"NO PARKING-STREET CLEANING",
"NO STAND TAXI/FHV RELIEF STAND",
"NO PARKING-TAXI STAND",
"NO PARKING-EXC. AUTH. VEHICLE",
"NO STANDING-COMMUTER VAN STOP",
"NO STANDING-FOR HIRE VEH STND",
"NO PARKING-EXC. DSBLTY PERMIT",
"OVERTIME STANDING DP",
"ALTERING INTERCITY BUS PERMIT",
"NO STOP/STANDNG EXCEPT PAS P/U",
"NO STANDING-COMM METER ZONE",
"OT PARKING-MISSING/BROKEN METR",
"FEEDING METER",
"EXPIRED METER",
"SELLING/OFFERING MCHNDSE-METER",
"PHTO SCHOOL ZN SPEED VIOLATION",
"EXPIRED MUNI METER",
",FAIL TO DSPLY MUNI METER RECPT",
",OVERTIME PKG-TIME LIMIT POSTED",
",FIRE HYDRANT",
",MISCELLANEOUS",
",EXPIRED MUNI MTR-COMM MTR ZN",
",EXPIRED METER-COMM METER ZONE",
",PKG IN EXC. OF LIM-COMM MTR ZN",
",TRAFFIC LANE",
",DOUBLE PARKING",
",DOUBLE PARKING-MIDTOWN COMML",
",BIKE LANE",
",EXCAVATION-VEHICLE OBSTR TRAFF",
",CROSSWALK",
",SIDEWALK",
",INTERSECTION",
",SAFETY ZONE",
",PCKP DSCHRGE IN PRHBTD ZONE",
",ELEVATED/DIVIDED HIGHWAY/TUNNL",
",DIVIDED HIGHWAY",
",BLUE ZONE",
",MARGINAL STREET/WATER FRONT",
",ANGLE PARKING-COMM VEHICLE",
",ANGLE PARKING",
",WRONG WAY",
",BEYOND MARKED SPACE",
",NIGHTTIME STD/ PKG IN A PARK",
",NO STANDING EXCP D/S",
",OVERTIME STDG D/S",
",DETACHED TRAILER",
",PEDESTRIAN RAMP",
",NON-COMPLIANCE W/ POSTED SIGN",
",FAIL TO DISP. MUNI METER RECPT",
",REG. STICKER-EXPIRED/MISSING",
",INSP. STICKER-EXPIRED/MISSING",
",INSP STICKER-MUTILATED/C'FEIT",
",REG STICKER-MUTILATED/C'FEIT",
",FRONT OR BACK PLATE MISSING",
",NO MATCH-PLATE/STICKER",
",VIN OBSCURED",
",PARKED BUS-EXC. DESIG. AREA",
",NGHT PKG ON RESID STR-COMM VEH",
",UNAUTHORIZED BUS LAYOVER",
",MISSING EQUIPMENT",
",NO STANDING EXCP DP",
",COMML PLATES-UNALTERED VEHICLE",
",IMPROPER REGISTRATION",
",PLTFRM LFTS LWRD POS COMM VEH",
",STORAGE-3HR COMMERCIAL",
",MIDTOWN PKG OR STD-3HR LIMIT",
",UNALTERED COMM VEHICLE",
",UNALTERED COMM VEH-NME/ADDRESS",
",NO STD(EXC TRKS/GMTDST NO-TRK)",
",VEH-SALE/WSHNG/RPRNG/DRIVEWAY",
",VEHICLE FOR SALE(DEALERS ONLY)",
",WASH/REPAIR VEHCL-REPAIR ONLY",
",REMOVE/REPLACE FLAT TIRE",
",RAILROAD CROSSING",
",VACANT LOT",
",OBSTRUCTING DRIVEWAY",
",OTHER"]
    let data = [515,
      515,
      515,
      115,
      115,
      265,
      50,
      115,
      115,
      115,
      115,
      95,
      115,
      115,
      115,
      95,
      95,
      115,
      115,
      65,
      65,
      115,
      65,
      65,
      115,
      115,
      180,
      95,
      515,
      515,
      115,
      65,
      65,
      65,
      65,
      50,
      65,
      65,
      65,
      115,
      0,
      65,
      65,
      65,
      115,
      115,
      115,
      115,
      95,
      115,
      115,
      115,
      115,
      115,
      115,
      115,
      65,
      65,
      115,
      65,
      65,
      65,
      95,
      95,
      95,
      65,
      165,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      65,
      115,
      60,
      95,
      115,
      65,
      65,
      65,
      115,
      115,
      115,
      115,
      40,
      65,
      65,
      65,
      95,
      65,
      95,
      105]
    var state = {
      labels: labels,
      datasets: [
        {
          label: "Fine Amount $",
          fill: false,
          lineTension: 0.5,
          backgroundColor: "rgba(75,192,192,1)",
          borderColor: "rgba(41, 128, 185,1)",
          borderWidth: 2,
          data: data,
          radius: 0
        }
      ]
    }
    return (
      <div >
        <Bar height="700px"
          data={state}
          options={{
            title: {
              display: true,
              text: "The total number of parking violation on Manhattan 96th St in 2008",
              fontSize: 20
            },
            legend: {
              display: false,
              position: "right"
            },
            // Boolean - whether or not the chart should be responsive and resize when the browser does.

            responsive: true,

            // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container

            maintainAspectRatio: false,
            pointRadius:0
          }}
        />
      </div>
    );
  }
}

export default ShowChart;
